generate_explanation:
  description: >
    Create a mathematical explanation that simulates a teacher explaining concepts while writing on a whiteboard.
    For the query: "{user_query}"

    Think of this as a teaching script where each step pairs:
    - Natural speech (what the teacher says while writing)
    - LaTeX math (what they write on the board at that moment)

    <output_format>
    {{
      "steps": [
        {{
          "natural": "What the teacher says during this step",
          "math": "The LaTeX notation they write while saying it"
        }}
      ]
    }}
    </output_format>

    Example:
    For "solve x^2 + 5x + 6 = 0":
    {{
      "steps": [
        {{
          "natural": "Let's solve this quadratic equation step by step. We'll start by writing down our equation.",
          "math": "x^2 + 5x + 6 = 0"
        }},
        {{
          "natural": "Looking at this, we can solve it by factoring. I'll rewrite it as two binomials...",
          "math": "(x + 2)(x + 3) = 0"
        }},
        {{
          "natural": "Now we can use the zero product property. When we set each factor to zero...",
          "math": "x + 2 = 0 \quad \text{{or}} \quad x + 3 = 0"
        }},
        {{
          "natural": "And solving these gives us our two solutions.",
          "math": "x = -2 \quad \text{{or}} \quad x = -3"
        }}
      ]
    }}

    Output Requirements:

    1. The first step must:
       - Begin with a clear introduction of what we're going to solve
       - Include "step by step" in the introduction
       - Present the initial problem or concept
    2. Subsequent steps should:
       - Flow naturally from the introduction
       - Build on previous steps
    3. Format requirements:
       natural: natural language ONLY formatted optimally for text-to-speech conversion
       math: LaTeX ONLY with correctly formatted LaTeX syntax 

  agent: math_teacher
  expected_output: "JSON with paired speech and LaTeX steps"

validate_latex:
  description: >
    Review the LaTeX notation and natural language pairs to ensure:
    1. LaTeX syntax is correct
    2. Natural speech flows well with the written math
    3. Each pair feels like a natural teaching moment

    For the original query: "{user_query}"

    The output should be in the same format as the input.

  agent: math_reviewer
  expected_output: "JSON with Validated or improved version of paired speech and LaTeX steps"
  context: 
    - generate_explanation
